name: CI

on:
  push:
    branches: [ main, develop ]
  workflow_dispatch: # This adds the manual "Run Workflow" button

jobs:
  call-workflow:
    uses: L-and-D-Management-System/LnD/.github/workflows/reusable-ci.yaml@main
    with:
      service_name: L-and-D-Management-System_auth-service_0f22a64f-770d-47af-ba80-436796307ac6
      image_name: auth-service
    secrets: inherit
